version: "3"

services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: flowstream_pg
    environment:
      POSTGRES_USER: flowstream
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flowstream
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data
    #
  redis:
    image: redis:latest
    container_name: flowstream_redis
    ports:
      - "6379:6379"
volumes:
  pgadmin:
