version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: flowstream_pg
    environment:
      POSTGRES_USER: flowstream
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: flowstream
    ports:
      - "5432:5432"
    # volumes:
    #   - ./postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: flowstream_redis
    ports:
      - "6379:6379"
    # volumes:
    #   - ./redis-data:/data
